### ISSUE TITLE
missing _this.eth.setRequestManager 

### ISSUE THREAD

**Issue by clemsos** [HardlyDifficult/hardlydifficult-eth#506]
Hello,

I am using the lib with hardhat and truffle5 and it is throwing the following error

```
TypeError: _this.eth.setRequestManager is not a function
```

This seems to be related to the way the truffle contract is initiated in the `helpers/truffleContract.js` and may relate do different versions of web3 or truffle being used.

Any ideas how to fix it?
Many thanks!

---

Here is the minimal test code

```js
const { constants, tokens, protocols } = require('hardlydifficult-eth')


contract('token', (accounts) => {
    const [protocolOwner] = accounts

    
    beforeEach(async () => {
        // Deploy the exchange
        const weth = await tokens.weth.deploy(web3, protocolOwner)
        const uniswapRouter = await protocols.uniswapV2.deploy(
            web3,
            protocolOwner,
            constants.ZERO_ADDRESS,
            weth.address
        )
    })

    it('exchange rate is > 0', async () => {
        assert.notEqual(1, 0)
    })
})
```

and the entire error

```sh
$ npx hardhat test test/errored.js                                                                                                                                                          1 ↵


  Contract: token
    1) "before each" hook for "exchange rate is > 0"
  0 passing (2s)
  1 failing

  1) Contract: token
       "before each" hook for "exchange rate is > 0":
     TypeError: _this.eth.setRequestManager is not a function
      at Web3Shim.Web3.setProvider (node_modules/hardlydifficult-eth/node_modules/@truffle/interface-adapter/node_modules/web3/lib/index.js:50:19)
      at new Web3Shim (node_modules/hardlydifficult-eth/node_modules/@truffle/interface-adapter/lib/shim/index.ts:68:14)
      at new Web3InterfaceAdapter (node_modules/hardlydifficult-eth/node_modules/@truffle/interface-adapter/lib/adapter/web3/index.ts:18:17)
      at createInterfaceAdapter (node_modules/hardlydifficult-eth/node_modules/@truffle/interface-adapter/lib/adapter/index.ts:23:14)
      at Function.configureNetwork (node_modules/hardlydifficult-eth/node_modules/@truffle/contract/lib/contract/constructorMethods.js:17:29)
      at Function.setProvider (node_modules/hardlydifficult-eth/node_modules/@truffle/contract/lib/contract/constructorMethods.js:40:10)
      at Object.new (node_modules/hardlydifficult-eth/src/helpers/truffleContract.js:16:14)
      at Object.deploy (node_modules/hardlydifficult-eth/src/tokens/weth.js:12:45)
      at Context.beforeEach (test/errored.js:10:40)
```

**Comment by NickCuso** [comment]
Ah yes, these helpers were specifically written with truffle in mind. I've been meaning to port this over to hardhat as well but haven't had the time.

**Comment by clemsos** [comment]
@NickCuso thanks for the answer. 

How will you go about porting them? Hardhat [supports Truffle testing](https://hardhat.org/guides/truffle-testing.html) so maybe it can be straighforward? Do you have pointers? I can look into it

**Comment by NickCuso** [comment]
I think I'd delete `helpers/truffleContract` and update code to work without any Truffle imports. ethers.js instead of web3 may be nice but with either it may need to accept a provider or signer to use instead of making assumptions.

The changes would just be in the src directory. The tests can be largerly unchanged and still use Truffle, but the changes may require small updates to the test for breaking changes.

**Comment by clemsos** [comment]
cool thx, will see if that can work

**Comment by NickCuso** [comment]
Also feel free to copy just the parts you need and migrate within your own project. There's a few things going on in this repo and it may not be very efficient to try and migrate the whole thing. ..if you do go that route, I'be be curious to see the end result.

**Comment by clemsos** [comment]
I ran the test suite in this repo with a basic hardhat config (below) and it worked like a charm, throwing a single error `Transaction reverted without a reason` which relates to the way hardhat handle returns VM errors I guess.

Also upgrading node to v14 seems to have solved my problem so I guess we can close this issue for now...

```
require("@nomiclabs/hardhat-truffle5");

module.exports = {
    solidity: {
        compilers: [
            { version: '0.6.0' },
            { version: '0.6.6' }
        ]  
    }
}
```

Also it appeared

**Comment by NickCuso** [comment]
Cool, thanks for the update
